### ISSUE TITLE
Beautiful Work

### ISSUE THREAD

**Issue by alwynallan** [bwshockley/Minifigure-SAMD21E#1]
It's the best thing shared on OSH Park recently. I hope there's a Kickstarter soon. An easy tool chain, like Teensyduino, would make it awesome, but I know it's a lot of work to create and maintain.

One little issue I noticed is the connection of the USB shield to ground. There's endless discussion in forums, with several camps:
  1. open circuit
  2. parallel RC to ground, typically 4.7nF and 1M
  3. 0603 ferrite bead to ground, they're cheap
  4. trace to ground

Since most USB Micro-B cables either don't have a shield, or don't connect it on the B side, you'll get away with 4. most times, but apparently it will not pass USB certification. For your application I would go with 1.

**Comment by bwshockley** [comment]
Thanks for the suggestions.  I'll take a look.  I had, at one point, gone with option #2 - but didn't want to place too many items on the underside.  Going with option #4 would be the easiest to implement.

I have updated the latest board with a layout capable of doing option 2 or with jumpers option 1.

Please see the board located under [board/2017/01/](https://github.com/bwshockley/Minifigure-SAMD21E/tree/master/board/2017/01)
